import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

export function renderPatch({ roles, corePersona, sharedTools }) {
  if (!Array.isArray(roles) || roles.length === 0) throw new TypeError('At least one role is required');
  if (typeof corePersona !== 'string' || !corePersona.trim()) throw new TypeError('Core persona is required');
  if (typeof sharedTools !== 'string' || !sharedTools.startsWith('          - id: ')) throw new TypeError('Shared tools require ten-space list indentation');
  const ids = new Set();
  for (const role of roles) {
    if (!role || typeof role.id !== 'string' || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(role.id) || ids.has(role.id)) throw new TypeError('Role ids must be unique lowercase identifiers');
    ids.add(role.id);
    for (const field of ['name', 'description', 'focus']) {
      if (typeof role[field] !== 'string' || !role[field].trim()) throw new TypeError(`Role ${role.id} requires ${field}`);
    }
    if (!Number.isFinite(role.order)) throw new TypeError(`Role ${role.id} requires a finite order`);
  }
  const quote = JSON.stringify;
  return '# Generated by scripts/build-presets.mjs; do not edit.\n- insert:\n' + roles.map(r => [
    `    - id: preset-${r.id}`,
    "      name: '@deepseek-ai/dsh-agent-preset'",
    '      config:',
    `        id: ${quote(r.id)}`,
    `        name: ${quote(r.name)}`,
    `        description: ${quote(r.description)}`,
    `        order: ${r.order}`,
    '        plugins:',
    '          - id: persona',
    "            name: '@deepseek-ai/dsh-persona'",
    '            config:',
    '              suffix: Your working directory is {{cwd}}.',
    `              prefix: ${quote(corePersona.trim() + '\n' + r.focus)}`,
    sharedTools.trimEnd(),
  ].join('\n')).join('\n') + '\n';
}

// Importing this module never generates files; CLI paths are independent of cwd.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2);
    if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) throw new Error('Usage: node scripts/build-presets.mjs [--check]');
    const { roles } = await import('../preset-src/roles.mjs');
    const read = path => readFileSync(new URL(path, import.meta.url), 'utf8');
    const output = renderPatch({roles, corePersona:read('../preset-src/core-persona.txt'), sharedTools:read('../preset-src/shared-tools.yml')});
    const target = new URL('../cordis.patch.yml', import.meta.url);
    if (args[0] === '--check') {
      if (readFileSync(target, 'utf8') !== output) throw new Error('Generated preset is stale; run npm run build:presets');
      console.log('Generated presets are current.');
    } else {
      writeFileSync(target, output);
      console.log(`Generated ${roles.length} GOLD presets.`);
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
